// Generated by https://quicktype.io

export interface Proveedor {
   // idUsuario: string;
    cedula:    string;
    nombres:   string;
    apellidos: string;
    telefono:  string;
    direccion: string;
    correo:    string;
}
